server {
    listen 80;
    listen [::]:80;
    server_name DEINE-DOMAIN.de www.DEINE-DOMAIN.de;

    root /var/www/hien-portfolio/current;
    index index.html;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
